

<a href='#' class='discord_banner'>
	<span class='ico_discord banner_icon'></span>
	<p class='banner_text'>Pounce onto our travel community</p>
</a>

<div class="space_l"></div>

<div id='footer_logo'>Meoweler</div>
<p class='ai_disclaimer'>Beware, most of the content was generated by AI</p>
<div id='finito'>
	<p class='madeby'>Made by <a href='#' class='softlink'>Vilem Ries</a></p>
	<a href='#' class='softlink footer_leaderboard'>MeowScore leaderboard</a>
</div>

<div class="space_m"></div>


<style>

.footer_leaderboard {
	font-size: 12px;
	display: inline-block;
	float: right;
}

.softlink {
	color: rgba(0, 0, 0, 1.0);
	text-decoration: none;
}

.madeby {
	float: left;
	font-size: 12px;
	color: rgba(0, 0, 0, 0.5);
}

#finito {
	width: calc(100% - 32px);
	margin: auto;
	margin-top: 32px;
}

.ai_disclaimer {
	margin-top: 8px;
	font-size: 12px;
	text-align: center;
	color: rgba(0, 0, 0, 0.5);
}

#footer_logo {
	margin: auto;
	text-align: center;
	font-family: Satoshi;
	font-size: 13px;
	font-weight: 500;
	letter-spacing: 1px;
	text-transform: uppercase;
}

.banner_icon {
	width: 48px;
	height: 48px;
	display: block;
	position: absolute;
	top: 10px;
	left: 10px;
}

.banner_text {
	font-size: 16px;
	font-weight: 500;
	line-height: 68px;
	margin-left: 64px;
	color: rgba(0, 0, 0, 1.0);
}

.discord_banner {
	width: calc(100% - 32px);
	height: 68px;
	margin: auto;
	border-radius: 20px;
	position: relative;
	display: block;
	text-decoration: none;
	background-color: rgba(240, 241, 253, 1.0);
}

.discord_banner:hover {
	background-color: rgba(230, 228, 253, 1.0);
}

</style>